= Contributing guidelines
:toc: macro
:toc-title:

First of all, thanks for taking the time and interest to contribute 🎉🎉🎉

Suggestions 💬 and pull requests 🔀 are always welcome!

The following is a set of guidelines for contributing to this repository.
These are mostly guidelines, not rules.

toc::[]

== Dependencies

The following set of dependencies is required for successfully developing this role.
Install them via your favorite Python package manager.

* https://docs.ansible.com/ansible/latest/index.html[Ansible]
* https://molecule.readthedocs.io/en/latest/[Molecule]
* https://pre-commit.com/[pre-commit]

== Testing

With Molecule installed it is simple to test changes locally.
In the root of this repository run `mol test` for a full test run.

During the implementation of a feature or fix a more iterative workflow makes sense:

* Run `mol converge` to provision a container via the `molecule/default/converge.yml` playbook.
* Run `mol login` to log into the container.
* Run `mol verify` to execute the checks in `molecule/default/verify.yml`.
* Run `mol destroy` to clean up when you are done.

[NOTE]
.Most development is done under Windows with WSL2
====
Since WSL2 has no systemd capabilities there is different Molecule configuration for local development (`molecule.yml`) and the CI pipeline (`molecule-ci.yml`):

* A non-systemd container is used for local development.
* https://podman.io/[Podman] is used instead of Docker.
  Either install the Molecule driver (`molecule-podman`) or use Docker locally.
====

== Styleguides

=== Git commit messages

The following style guide reflects personal preferences as well as best practices as described in the https://git-scm.com/book/ch5-2.html[Pro Git book].

* Limit the first line to 50 characters or less.
* Start the first line with an applicable emoji from https://gitmoji.dev/.
* Use the present tense.
+
[source,diff]
----
-✨ Added feature xyz
+✨ Add feature xyz
----
* Use the imperative mood.
+
[source,diff]
----
-✨ Adds feature xyz
+✨ Add feature xyz
----
* Do *not* end the commit title with a period.
+
[source,diff]
----
-✨ Add feature xyz.
+✨ Add feature xyz
----
* Leave a blank line between title and body.
* Limit remaining lines to 72 characters or less.
* You may use the message body to provide additional information
+
[source]
.Full example adapted from https://git-scm.com/book/ch5-2.html
----
📝 Capitalized, short (50 chars or less) summary

More detailed explanatory text, if necessary. The blank line separating
the summary from the body is critical (unless you omit the body
entirely); tools like rebase will confuse you if you run the two
together.

Further paragraphs come after blank lines.

* Bullet points are okay, too
* Typically a hyphen or asterisk is used for the bullet, followed by a
  single space
* Use a hanging indent
----

NOTE: You may reference issues and pull requests liberally in the message body.
