# Ansible role: {{ cookiecutter.role }}

image:https://github.com/DAG-OS/ansible-role-{{ cookiecutter.role_name }}/actions/workflows/ci.yml/badge.svg?branch=trunk[CI,link=https://github.com/DAG-OS/ansible-role-{{ cookiecutter.role_name }}/actions/workflows/ci.yml]
image:https://github.com/DAG-OS/ansible-role-{{ cookiecutter.role_name }}/actions/workflows/release.yml/badge.svg[Release,link=https://github.com/DAG-OS/ansible-role-{{ cookiecutter.role_name }}/actions/workflows/release.yml]
// TODO: Add ansible role ID to badges once it is released
// Use following command:
//    ansible-galaxy info {{ cookiecutter.role }} | grep -E 'id: [0-9]' | awk {'print $2'}
//image:https://img.shields.io/ansible/quality/<ansible-role-id>?logo=ansible[Quality,link=https://galaxy.ansible.com/dagos/{{ cookiecutter.role_name }}]
//image:https://img.shields.io/ansible/role/d/<ansible-role-id>?logo=ansible[Downloads,link=https://galaxy.ansible.com/dagos/{{ cookiecutter.role_name }}]

{{ cookiecutter.role_description }}

## Requirements

None.

## Role variables

The following variables are overridable by users to configure this role:

[source,yaml]
.https://github.com/DAG-OS/ansible-role-{{ cookiecutter.role_name }}/blob/trunk/defaults/main.yml[defaults/main.yml]
----
include::example$defaults-main.yml[]
----

## Dependencies

None.

## Example playbook

The following playbook is tested regularly as part of the defined CI pipeline:

[source,yaml]
.https://github.com/DAG-OS/ansible-role-{{ cookiecutter.role_name }}/blob/trunk/molecule/default/converge.yml[molecule/default/converge.yml]
----
include::example$converge.yml[]
----

## License

MIT

## Author information

This role was created in {% now 'local', '%Y' %} by {{ cookiecutter.full_name }}.
